CHUNK_SIZE = 400
CHUNK_OVERLAP = 50

DEFAULT_MAX_WORKERS = 4
DEFAULT_PDF_PAGE_IMAGE_DPI = 300
DEFAULT_PDF_PAGES_TO_SUMMARIZE = 10

DEFAULT_MAX_RECURSIONS = 30
DEFAULT_MAX_TOTAL_TOKENS = 250_000
DEFAULT_AGENT_RETRY_ATTEMPTS = 1
DEFAULT_AGENT_CONTEXT_TOKENS = 3000

# Search result limits - keep results lean
DEFAULT_SEARCH_RESULT_LIMIT = 3
MAX_SEARCH_RESULT_LIMIT = 5
DEFAULT_CHUNK_WINDOW_RADIUS = 3

# Document retrieval limits
MAX_DOCUMENT_CHUNK_WINDOW = 100
DEFAULT_MAX_SEARCH_OPERATIONS = 4
MAX_TOOL_TOKENS = 1000

# Embedding model
EMBEDDING_MODEL = "BAAI/bge-base-en-v1.5"

# Primary agent round defaults
DEFAULT_MAX_TODO_ROUNDS = 10
DEFAULT_MAX_TOTAL_ROUNDS = DEFAULT_MAX_TODO_ROUNDS + 1
